#!/bin/sh

if [ ! -e amazon-ssm-agent ] ; then
  echo getting SSM source code
  git clone https://github.com/aws/amazon-ssm-agent.git
fi

cd amazon-ssm-agent || exit

# amazon-ssm-agent
echo "Running on agent, errors in taint-errors.txt"
../bin/argot-cli -config ../testdata/config-examples/config-agent.yaml \
              agent/agent.go \
              agent/agent_unix.go \
              agent/agent_parser.go
