#!/bin/sh

if [ ! -e amazon-ssm-agent ] ; then
  echo getting SSM source code
  git clone https://github.com/aws/amazon-ssm-agent.git
fi

cd amazon-ssm-agent || exit

# amazon-ssm-agent
echo "Running render callgraph on agent"
../bin/render -config ../testdata/config-examples/config-agent.yaml -cgout callgraph.dot \
              agent/agent.go \
              agent/agent_unix.go \
              agent/agent_parser.go
