#!/bin/sh

if [ ! -e amazon-ssm-agent ] ; then
  echo getting SSM source code
  git clone https://github.com/aws/amazon-ssm-agent.git
fi

cd amazon-ssm-agent

#export GOPATH=`pwd`/vendor

#OPT="--dependency-analysis"

# amazon-ssm-agent
echo amazon-ssm-agent
../bin/dependencies core/agent.go core/agent_unix.go core/agent_parser.go

echo

# ssm-agent-worker
echo ssm-agent-worker
../bin/dependencies agent/agent.go agent/agent_unix.go agent/agent_parser.go

echo

# updater
echo updater
../bin/dependencies  agent/update/updater/updater.go agent/update/updater/updater_unix.go

echo

# ssm-cli
echo ssm-cli
../bin/dependencies agent/cli-main/cli-main.go

echo

# ssm-document-worker
echo ssm-document-worker
../bin/dependencies agent/framework/processor/executer/outofproc/worker/main.go

echo

# ssm-session-logger
echo ssm-session-logger
../bin/dependencies agent/session/logging/main.go

echo

# ssm-session-worker
echo ssm-session-worker
../bin/dependencies agent/framework/processor/executer/outofproc/sessionworker/main.go
