#!/bin/sh

if [ ! -e scripts/ssm-callgraph ] ; then
  echo "Error: run this script from argot root directory"
  exit 1
fi
if [ ! -e amazon-ssm-agent ] ; then
  echo getting SSM source code
  git clone https://github.com/aws/amazon-ssm-agent.git
fi

cd amazon-ssm-agent

CALLGRAPHDIR=/tmp/gocoverdir

if [ ! -e "$CALLGRAPHDIR" ] ; then
  echo "Error: this script requires dynamic callgraphs recorded from an instrumented binary"
  echo "Generate these by running (for an example program in main.go):"
  echo "  go build -cover main.go ..."
  echo "  mkdir /tmp/gocoverdir"
  echo "  GOCOVERDIR=/tmp/gocoverdir ./main ..."
  echo "This requires the callgraph-instrumentation version of the go compiler and runtime."
  exit 1
fi

echo "Core agent"
../bin/compare -analysis pointer -dynbinary amazon-ssm-agent -callgraphs "$CALLGRAPHDIR" \
  core/agent.go core/agent_unix.go core/agent_parser.go
echo "Agent worker"
../bin/compare -analysis pointer -dynbinary ssm-agent-worker -callgraphs "$CALLGRAPHDIR" \
  agent/agent.go agent/agent_unix.go agent/agent_parser.go
echo "Document worker"
../bin/compare -analysis pointer -dynbinary ssm-document-worker -callgraphs "$CALLGRAPHDIR" \
  agent/framework/processor/executer/outofproc/worker/main.go
echo "Session worker"
../bin/compare -analysis pointer -dynbinary ssm-session-worker -callgraphs "$CALLGRAPHDIR" \
  agent/framework/processor/executer/outofproc/sessionworker/main.go

# ../bin/render -analysis pointer -htmlout document-worker.html \
#   agent/framework/processor/executer/outofproc/worker/main.go
