// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package check

import (
	"go/types"
	"slices"
	"strings"

	"github.com/awslabs/ar-go-tools/analysis/dataflow"
	"github.com/awslabs/ar-go-tools/analysis/summaries"
	"golang.org/x/tools/go/ssa"
)

// An access path bound decides how long access paths may get, and therefore which access paths a
// summary can tell apart. It is the parameter a summary must be read against: a flow between two
// access paths that truncate to the same access path is *implicit*, because the summary format has no
// way to write it down -- a row from a path to itself says nothing. So a summary read at one bound and
// the identical summary read at a finer bound make different claims, and a summary proved sound at one
// bound is not thereby sound at another.
//
// A bound is not a single depth. It is a tree over field names, per position, so the descent can stop
// at different depths on different branches. Truncation is total: every access path has a truncation,
// and truncating twice is truncating once.
//
// The bound a summary is read against is computed from the summary itself, by boundOfSummary: it
// extends exactly as deep as the longest access path the summary mentions under each position. A
// summary mentioning no field under a position is read field-insensitively there, which is why an
// empty summary admits every flow within a position.
//
// When several call sites enter one callee position at different depths, the callee's bound must be at
// least as fine as every one of them (see join). Taking the shallowest instead places two access paths
// under one name that a finer call site told apart, so a flow between them becomes implicit -- and a
// caller that discharged a must-not-flow by relying on the callee lacking that flow is then relying on
// something no summary at that bound can assert.

// lengthBound is how far access paths under one position may be extended.
//
// The zero value is the maximum length: an access path reaching this point is as long as the bound
// admits, and anything longer truncates to it. This is the field-insensitive reading, the paper's
// k = 0. Otherwise extend gives the bound beneath each field, and a field absent from it is itself
// maximal -- so a missing map key already means the right thing, and the canonical form omits fields
// whose own bound is maximal.
type lengthBound struct {
	extend map[string]lengthBound
}

// isMaximal reports whether the descent stops here.
func (b lengthBound) isMaximal() bool { return b.extend == nil }

// truncate returns the longest prefix of p this bound admits. It is total, idempotent, and always
// returns a path that subsumes p.
func (b lengthBound) truncate(p path) path {
	cur := b
	n := p.len()
	for i := range n {
		if cur.isMaximal() {
			return p.truncate(i)
		}
		sub, ok := cur.extend[p[i]]
		if !ok {
			// The field may be named but not descended into, so keep it and stop.
			return p.truncate(i + 1)
		}
		cur = sub
	}
	return p
}

// refines reports whether b admits every access path other admits, i.e. whether b is at least as fine.
// Reading a summary at a bound that refines the one it was checked at claims strictly less, so
// soundness does not transfer in that direction.
func (b lengthBound) refines(other lengthBound) bool {
	if other.isMaximal() {
		return true
	}
	if b.isMaximal() {
		return false
	}
	for f, ob := range other.extend {
		if !b.extend[f].refines(ob) {
			return false
		}
	}
	return true
}

// joinLengthBounds returns the coarsest bound refining both: field by field, whichever descends
// further. This is what a callee position needs when its call sites enter it at different depths.
func joinLengthBounds(a, b lengthBound) lengthBound {
	if a.isMaximal() {
		return b
	}
	if b.isMaximal() {
		return a
	}
	m := make(map[string]lengthBound, len(a.extend)+len(b.extend))
	for f, ab := range a.extend {
		m[f] = joinLengthBounds(ab, b.extend[f])
	}
	for f, bb := range b.extend {
		if _, seen := m[f]; !seen {
			m[f] = joinLengthBounds(a.extend[f], bb)
		}
	}
	return lengthBound{extend: m}
}

// boundOfPaths returns the bound generated by a set of access paths: it descends exactly as far as the
// longest of them along each branch. An empty set yields the maximal bound, which is why a summary
// mentioning no field under a position is read field-insensitively there.
func boundOfPaths(ps []path) lengthBound {
	byField := make(map[string][]path)
	mentionsField := false
	for _, p := range ps {
		if p.len() == 0 {
			continue
		}
		mentionsField = true
		var tail path
		for i := 1; i < p.len(); i++ {
			tail[i-1] = p[i]
		}
		byField[p[0]] = append(byField[p[0]], tail)
	}
	if !mentionsField {
		return lengthBound{}
	}
	m := make(map[string]lengthBound, len(byField))
	for f, tails := range byField {
		if sub := boundOfPaths(tails); !sub.isMaximal() {
			m[f] = sub
		}
	}
	return lengthBound{extend: m}
}

func (b lengthBound) String() string {
	if b.isMaximal() {
		return "*"
	}
	fields := make([]string, 0, len(b.extend))
	for f := range b.extend {
		fields = append(fields, f)
	}
	slices.Sort(fields)
	var sb strings.Builder
	sb.WriteString("{")
	for i, f := range fields {
		if i > 0 {
			sb.WriteString(" ")
		}
		sb.WriteString(f)
		sb.WriteString(b.extend[f].String())
	}
	sb.WriteString("}")
	return sb.String()
}

// pathsOfTypeUnderBound returns a *partition* of the memory under t: one access path per branch where
// the bound stops descending, each standing for the whole subtree beneath it. Together they cover every
// byte of the position exactly once.
//
// It is not the set of access paths the bound admits. A path shorter than the bound -- the position
// itself, or an interior node like .Dst when the bound reaches .Dst.X -- is left out, because it is not
// a representative: it names memory that the returned paths already cover between them.
//
// Partitioning is what makes this the right set to seed the analysis with and to build the most-general
// summary over. Tainting every element is equivalent to tainting the whole position, and a flow out of
// an interior node induces a flow out of at least one element beneath it, since the interior node's data
// is exactly the union of theirs. So quantifying over these paths loses no flow.
//
// Structural types that do not name a field -- pointers, named types, arrays, slices, maps -- do not
// consume depth, matching how access paths are parsed.
func pathsOfTypeUnderBound(t types.Type, b lengthBound) []path {
	type frame struct {
		t types.Type
		p path
		d int
		b lengthBound
	}
	var res []path
	stack := []frame{{t: t, p: path{}, d: 0, b: b}}
	for len(stack) > 0 {
		cur := stack[len(stack)-1]
		stack = stack[:len(stack)-1]

		// The bound stops here, so this path stands for everything beneath it.
		if cur.b.isMaximal() || cur.d == maxPathLen {
			res = append(res, cur.p)
			continue
		}

		switch ty := cur.t.(type) {
		case *types.Pointer:
			stack = append(stack, frame{t: ty.Elem(), p: cur.p, d: cur.d, b: cur.b})
		case *types.Named:
			stack = append(stack, frame{t: ty.Underlying(), p: cur.p, d: cur.d, b: cur.b})
		case *types.Array:
			stack = append(stack, frame{t: ty.Elem(), p: cur.p, d: cur.d, b: cur.b})
		case *types.Slice:
			stack = append(stack, frame{t: ty.Elem(), p: cur.p, d: cur.d, b: cur.b})
		case *types.Map:
			stack = append(stack, frame{t: ty.Elem(), p: cur.p, d: cur.d, b: cur.b})
		case *types.Struct:
			if ty.NumFields() == 0 {
				// Nowhere left to descend, so the position is itself a leaf.
				res = append(res, cur.p)
				continue
			}
			for i := range ty.NumFields() {
				fld := ty.Field(i)
				next := cur.p
				next[cur.d] = fld.Name()
				// A field the bound does not descend into is maximal, so it is emitted as a leaf on
				// the next iteration.
				stack = append(stack, frame{
					t: fld.Type(), p: next, d: cur.d + 1, b: cur.b.extend[fld.Name()],
				})
			}
		default:
			res = append(res, cur.p)
		}
	}
	return res
}

// nodeBounds is the bound at each position of one function, keyed by that function's own dataflow
// nodes. It is the in-graph form of a pathBound: a pathBound names positions portably, so a bound can
// travel with a summary into a callee's own check, while nodeBounds names them by the graph under
// analysis.
//
// A node absent from at is maximal, so the zero value reads every position field-insensitively and is
// safe to both read from and record into.
type nodeBounds struct {
	at map[dataflow.GraphNode]lengthBound
}

// truncate returns the access path that represents p at n's bound.
func (nb nodeBounds) truncate(n dataflow.GraphNode, p path) path {
	return nb.at[n].truncate(p)
}

// implicit reports whether a flow between a and b at n is implied by any summary read at these
// bounds, because the two truncate to the same access path.
func (nb nodeBounds) implicit(n dataflow.GraphNode, a, b path) bool {
	return nb.truncate(n, a) == nb.truncate(n, b)
}

// paths returns the access paths of n that its bound admits, which is exactly the set a summary read
// at these bounds can name.
func (nb nodeBounds) paths(n dataflow.GraphNode) []path {
	return pathsOfTypeUnderBound(n.Type(), nb.at[n])
}

// record widens n's bound so that it admits p.
func (nb *nodeBounds) record(n dataflow.GraphNode, p path) {
	if nb.at == nil {
		nb.at = make(map[dataflow.GraphNode]lengthBound)
	}
	nb.at[n] = joinLengthBounds(nb.at[n], boundOfPaths([]path{p}))
}

// set replaces n's bound, dropping maximal entries so the map stays canonical.
func (nb *nodeBounds) set(n dataflow.GraphNode, b lengthBound) {
	if b.isMaximal() {
		return
	}
	if nb.at == nil {
		nb.at = make(map[dataflow.GraphNode]lengthBound)
	}
	nb.at[n] = b
}

// maxDepth is the deepest access path any position admits. The intra-procedural taint analysis takes
// a single scalar precision for the whole function, so this is the one place a bound has to be
// flattened; every decision the checker itself makes stays per position.
func (nb nodeBounds) maxDepth() int {
	depth := 0
	for _, b := range nb.at {
		depth = max(depth, b.depth())
	}
	return depth
}

// boundsOfFlows returns the bound each node is named at by the given flow sets, taking both endpoints
// of every flow. Inputs and outputs share one bound per node, because a position that is both -- a
// pointer parameter -- is one piece of memory that the summary format names the same way on both
// sides.
func boundsOfFlows(flowSets ...[]flow) nodeBounds {
	byNode := make(map[dataflow.GraphNode][]path)
	note := func(sn summaryNode) {
		if !slices.Contains(byNode[sn.node], sn.path) {
			byNode[sn.node] = append(byNode[sn.node], sn.path)
		}
	}
	for _, flows := range flowSets {
		for _, fl := range flows {
			note(fl.from)
			note(fl.to)
		}
	}
	var nb nodeBounds
	for n, ps := range byNode {
		nb.set(n, boundOfPaths(ps))
	}
	return nb
}

// widenTo widens every position of g that v names, so a bound demanded by a caller survives into the
// callee's own check. Positions the exported summary vocabulary cannot name -- globals -- stay
// field-insensitive.
func (nb *nodeBounds) widenTo(g *dataflow.SummaryGraph, v pathBound) {
	if len(v.at) == 0 {
		return
	}
	g.ForAllNodes(func(n dataflow.GraphNode) {
		sn, ok := frontendNode(summaryNode{node: n})
		if !ok {
			return
		}
		b := v.at[newBoundPosition(sn)]
		if b.isMaximal() {
			return
		}
		nb.set(n, joinLengthBounds(nb.at[n], b))
	})
}

// toPathBound projects these bounds into the portable vocabulary, so they can cross into a callee's
// own check. Positions with no exported name are dropped, which reads them field-insensitively.
func (nb nodeBounds) toPathBound() pathBound {
	var v pathBound
	for n, b := range nb.at {
		sn, ok := frontendNode(summaryNode{node: n})
		if !ok {
			continue
		}
		pos := newBoundPosition(sn)
		v.set(pos, joinLengthBounds(v.at[pos], b))
	}
	return v
}

// depth is the deepest access path this bound admits.
func (b lengthBound) depth() int {
	if b.isMaximal() {
		return 0
	}
	deepest := 0
	for _, sub := range b.extend {
		deepest = max(deepest, sub.depth())
	}
	return deepest + 1
}

// boundPosition names a position in a function's signature without pointing into any dataflow graph,
// so a bound computed while checking a caller still names the same position when that callee is
// checked on its own. Object paths are always empty: the path is what the bound is about.
//
// Positions a dataflow graph has but the exported summary vocabulary does not -- globals in
// particular -- cannot be named here, and are read field-insensitively.
type boundPosition struct {
	node summaries.SummaryNode
}

func newBoundPosition(sn summaries.SummaryNode) boundPosition {
	return boundPosition{node: sn.WithObjectPath("")}
}

// pathBound is the bound a summary is read against: one lengthBound per position. A position absent
// from at is maximal, so the zero value reads every position field-insensitively and is safe to both
// read from and record into.
//
// Inputs and outputs share one bound per position, because a position that is both -- a pointer
// parameter -- is one piece of memory, and the summary format names it the same way on both sides.
type pathBound struct {
	at map[boundPosition]lengthBound
}

// truncate returns the access path that represents p at this bound.
func (v pathBound) truncate(pos boundPosition, p path) path {
	return v.at[pos].truncate(p)
}

// implicit reports whether a flow between a and b at pos is implied by any summary read at v, because
// the two truncate to the same access path. No summary at v can deny such a flow.
func (v pathBound) implicit(pos boundPosition, a, b path) bool {
	return v.truncate(pos, a) == v.truncate(pos, b)
}

// distinguishes reports whether v tells a and b apart, so that a summary read at v can deny a flow
// between them.
func (v pathBound) distinguishes(pos boundPosition, a, b path) bool {
	return !v.implicit(pos, a, b)
}

// record widens the bound at pos so that it admits p.
func (v *pathBound) record(pos boundPosition, p path) {
	if v.at == nil {
		v.at = make(map[boundPosition]lengthBound)
	}
	v.at[pos] = joinLengthBounds(v.at[pos], boundOfPaths([]path{p}))
}

// refines reports whether v admits every access path other admits, at every position.
func (v pathBound) refines(other pathBound) bool {
	for pos, ob := range other.at {
		if !v.at[pos].refines(ob) {
			return false
		}
	}
	return true
}

// join returns the coarsest bound refining both, position by position.
func (v pathBound) join(other pathBound) pathBound {
	var res pathBound
	for pos, b := range v.at {
		res.set(pos, joinLengthBounds(b, other.at[pos]))
	}
	for pos, b := range other.at {
		if _, seen := res.at[pos]; !seen {
			res.set(pos, joinLengthBounds(v.at[pos], b))
		}
	}
	return res
}

func (v *pathBound) set(pos boundPosition, b lengthBound) {
	if b.isMaximal() {
		return
	}
	if v.at == nil {
		v.at = make(map[boundPosition]lengthBound)
	}
	v.at[pos] = b
}

func (v pathBound) String() string {
	keys := make([]boundPosition, 0, len(v.at))
	for pos := range v.at {
		keys = append(keys, pos)
	}
	slices.SortFunc(keys, func(a, b boundPosition) int {
		return strings.Compare(a.node.String(), b.node.String())
	})
	var sb strings.Builder
	sb.WriteString("{")
	for i, pos := range keys {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(pos.node.String())
		sb.WriteString(":")
		sb.WriteString(v.at[pos].String())
	}
	sb.WriteString("}")
	return sb.String()
}

// boundOfSummary returns the bound a summary is read against: under each position, it extends exactly
// as deep as the longest access path the summary mentions there.
//
// This is the only place a bound is derived from a summary's syntax. Everywhere else a bound travels
// with the summary, because recomputing it at the callee would recover the callee's own reading rather
// than the caller's demand.
func boundOfSummary(summ summaries.DetailedSummary) pathBound {
	byPos := make(map[boundPosition][]path)
	note := func(sn summaries.SummaryNode) {
		pos := newBoundPosition(sn)
		p := newPath(sn.Path(), maxPathLen)
		if !slices.Contains(byPos[pos], p) {
			byPos[pos] = append(byPos[pos], p)
		}
	}
	for from, tos := range summ.Flows {
		note(from)
		for _, to := range tos {
			note(to)
		}
	}
	var res pathBound
	for pos, ps := range byPos {
		res.set(pos, boundOfPaths(ps))
	}
	return res
}

// calleeBounds is the bound chosen for each callee, the counterpart of the summaries deduced for them.
// A callee's bound is one set of facts shared by all of its call sites, so it must refine what every
// site demands. A callee absent from the map is read field-insensitively.
type calleeBounds map[*ssa.Function]pathBound

// demand widens the bound for callee f so that it admits p at pos.
func (cb calleeBounds) demand(f *ssa.Function, pos boundPosition, p path) {
	v := cb[f]
	v.record(pos, p)
	cb[f] = v
}
