on:
  pull_request:
    branches:
      - mainline
  push:
    branches:
      - mainline
  schedule:
    - cron: '30 15 * * 1,3'

name: build-analyze-test

env:
  GIT_SUBMODULE_STRATEGY: recursive

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.22.7', '1.23']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup dependencies
        run: |
          go mod download
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.1
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install github.com/gordonklaus/ineffassign@latest
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/deadcode@latest
      - name: Run basic analyses
        run: |
          go vet ./...
          gocyclo -ignore "test|internal/pointer|internal/typeparams" -over 15 .
          ineffassign ./...
          golint -set_exit_status -min_confidence 0.9 ./...
      - name: Run vulnerability checking
        run: |
          govulncheck ./...
      - name: Build Argot executable
        run: |
          make argot-build
      - name: Build racerg executable
        run: |
          make racerg-build
      - name: Test
        run: go test -coverprofile=coverage.txt -covermode count ./analysis/...
